boards/urls.py
from django.urls import path

from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.board_index, name='board_index'),
    path('project/<int:board_id>', views.board_index_name, name='board_index_name'),
    path('login/', views.board_login, name='board_login'),
    path('logout/', views.board_logout, name='board_logout'),
    path('agreement/', views.board_agreement, name='board_agreement'),
    path('register/', views.board_register, name='board_register'),

    # path('write/', views.board_write, name='board_write'),
    path('delete/<int:article_id>', views.board_delete, name='board_delete'),
    path('delete_fix/', views.board_delete_fix, name='board_delete_fix'),

    path('edit/<int:article_id>', views.board_edit, name='board_edit'),
    path('edit_fix/', views.board_edit_fix, name='board_edit_fix'),

    path('<int:article_id>/', views.board_detail, name='board_detail'),

    path('vote/<int:article_id>', views.board_vote, name='board_vote'),

    path('comment/', views.board_comment_write, name='board_comment_write'),
    path('comment_vote/<int:comment_id>', views.board_comment_vote, name='board_comment_vote'),
    path('comment_delete/<int:comment_id>', views.board_comment_delete, name='board_comment_delete'),
    path('profile/<int:user_id>', views.board_profile, name='board_profile'),

    path('navigatior/', views.board_navigator, name='board_navigator'),
    path('navigatior/<int:board_id>', views.board_navigator_under, name='board_navigator_under'),
    path('projectCreatePage/', views.board_create_project_page, name='board_create_project_page'),
    path('projectCreate/', views.board_create_project, name='board_create_project'),

    path('write/', views.board_write, name='board_write'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

tutorialPoll/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

from boards.views import assetlink

urlpatterns = [
    path('', include('boards.urls')),
    # path('todaycomment/', include('todaycomment.urls')),
    # path('boards/', include('boards.urls')),
    # path('polls/', include('polls.urls')),
    path('say/admin/', admin.site.urls),

    re_path(r'^summernote/', include('django_summernote.urls')),

    re_path(r'^\.well-known/assetlinks\.json', assetlink.as_view()),

    path('API/', include('router.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boards/views.py
from django.shortcuts import render
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.http.response import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from datetime import timedelta

from django.db.models import F

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, get_user, login, logout

from django.views.generic import TemplateView

from django.utils import timezone

from django.shortcuts import get_object_or_404, Http404

from django.conf import settings

from .models import Article, ArticleIpLog, Comment, CommentIpLog, Board
from .models import Attachment, Board, AdditionalUserProfile, BoardImage, UserProfileImage
from .form import BasicForm, UserRegisterForm, UserRegisterFormOptional

from bs4 import BeautifulSoup

from .viewsPartial.view_comment import board_comment_delete, board_comment_vote, board_comment_write


class assetlink(TemplateView):
    template_name = "boards/assetlinks.json"
    content_type = "application/json"


def board_index(request):
    user = get_user(request)
    article_list_top = Article.objects.filter(published=True, activated=True, created_at__gte=timezone.now() - timedelta(days=3)).order_by('upvote').reverse()[:8]
    article_list = Article.objects.filter(published=True, activated=True).reverse()

    template = 'boards/board_index.html'
    page_fragment = 'boards/board_index_fragment.html'

    if request.is_ajax():
        template = page_fragment

    if user.is_authenticated :
        return render(request, template, {'user': user,
                                          'page_fragment': page_fragment,
                                          'article_list': article_list,
                                          'article_list_top': article_list_top})
    else:
        return render(request, template, {'article_list': article_list,
                                          'page_fragment': page_fragment,
                                          'article_list_top': article_list_top})


def board_index_name(request, board_id):
    user = get_user(request)
    board = get_object_or_404(Board, pk=board_id)
    article_list_top = Article.objects.filter(board_id=board_id, published=True, activated=True, created_at__gte=timezone.now() - timedelta(days=3)).order_by('upvote').reverse()[:8]
    article_list = Article.objects.filter(board_id=board_id, published=True, activated=True).reverse()

    template = 'boards/board_index.html'
    page_fragment = 'boards/board_index_fragment.html'

    if request.is_ajax():
        template = page_fragment

    if user.is_authenticated :
        return render(request, template, {'user': user,
                                          'board': board,
                                          'page_fragment': page_fragment,
                                          'article_list': article_list,
                                          'article_list_top': article_list_top})
    else:
        return render(request, template, {'article_list': article_list,
                                          'board': board,
                                          'page_fragment': page_fragment,
                                          'article_list_top': article_list_top})


# def board_index_name(request, board_url=''):
#     user = get_user(request)
#     article_list = Article.objects.filter(board_name__url=board_url, published=True, activated=True)
#     if user.is_authenticated :
#         return render(request, 'boards/board_index.html', {'user': user,
#                                                            'article_list': article_list,
#                                                            })
#     else:
#         return render(request, 'boards/board_index.html', {'article_list': article_list})


def board_detail(request, article_id):
    user = get_user(request)
    A = get_object_or_404(Article, pk=article_id)
    if A.published and A.activated:
        if user.is_authenticated:
            # article_list = Article.objects.filter(published=True, activated=True).order_by('upvote').reverse()
            C = Comment.objects.filter(article_id=article_id)
            A.hit += 1
            A.save()
            return render(request, 'boards/board_detail.html', {'article_detail': A,
                                                                'user': user,
                                                                'comment_list': C})
        else:
            # article_list = Article.objects.filter(published=True, activated=True).order_by('upvote').reverse()
            C = Comment.objects.filter(article_id=article_id)
            A.hit += 1
            A.save()
            return render(request, 'boards/board_detail.html', {'article_detail': A,
                                                                'comment_list': C})
    else:
        return Http404()
        # article_list_top = Article.objects.filter(published=True, activated=True,
        #                                           created_at__gte=timezone.now() - timedelta(days=3)).order_by(
        #     'upvote').reverse()[:8]
        # article_list = Article.objects.filter(published=True, activated=True).reverse()
        #
        # if user.is_authenticated:
        #     return render(request, 'boards/board_index.html', {'user': user,
        #                                                        'article_list': article_list,
        #                                                        'article_list_top': article_list_top,
        #                                                        'error_message': '볼 수 없는 게시물입니다.'})
        # else:
        #     return render(request, 'boards/board_index.html', {'article_list': article_list,
        #                                                        'article_list_top': article_list_top,
        #                                                        'error_message': '볼 수 없는 게시물입니다.'})


def board_vote(request, article_id):
    A = get_object_or_404(Article, pk=article_id)
    user = get_user(request)
    user_ip = get_client_ip(request)
    if ArticleIpLog.objects.filter(ip=user_ip, article=A).exists():
        return HttpResponseRedirect(reverse('boards:board_detail', kwargs={'article_id': article_id}))
    else:
        if get_user(request).is_active:
            ArticleIpLog.objects.create(ip=user_ip,
                                        user=user,
                                        article=A,
                                        created_at=timezone.now())
        else:
            ArticleIpLog.objects.create(ip=user_ip,
                                        article=A,
                                        created_at=timezone.now())
        if request.method == 'POST':
            if request.POST['vote'] == 'up':
                A.upvote += 1
                A.save()
                return HttpResponseRedirect(reverse('boards:board_detail', kwargs={'article_id': article_id}))
            if request.POST['vote'] == 'down':
                A.downvote += 1
                A.save()
                return HttpResponseRedirect(reverse('boards:board_detail', kwargs={'article_id': article_id}))
            # up이랑 down 이랑 안되는 케이스도 어떻게 커버하는게 좋을듯
        elif request.method == 'GET':
            if request.GET['vote'] == 'up':
                A.upvote += 1
                A.save()
                return HttpResponseRedirect(reverse('boards:board_detail', kwargs={'article_id': article_id}))
            if request.GET['vote'] == 'down':
                A.downvote += 1
                A.save()
                return HttpResponseRedirect(reverse('boards:board_detail', kwargs={'article_id': article_id}))
        else:
            return HttpResponseRedirect(reverse('boards:board_detail', kwargs={'article_id': article_id}))


def board_login(request):
    user = get_user(request)
    if user.is_authenticated:
        article_list_top = Article.objects.filter(published=True, activated=True,
                                                  created_at__gte=timezone.now() - timedelta(days=3)).order_by(
            'upvote').reverse()[:8]
        article_list = Article.objects.filter(published=True, activated=True).reverse()
        return render(request, 'boards/board_index.html', {'user': user,
                                                           'article_list': article_list,
                                                           'article_list_top': article_list_top,
                                                           'error_message': '이미 로그인 되어있습니다'
                                                           })
    else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request,
                                username=username,
                                password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('boards:board_index'))
            else:
                return render(request, 'boards/board_login.html', {'error_message': '아이디 혹은 비밀번호가 틀립니다.'})
        else:
            return render(request, 'boards/board_login.html')


def board_logout(request):
    user = get_user(request)
    if user.is_authenticated:
        logout(request)
        return HttpResponseRedirect(reverse('boards:board_index'))
    return HttpResponseRedirect(reverse('boards:board_index'))


def board_register(request):
    if request.method == 'POST':
        form_required = UserRegisterForm(data=request.POST)
        form_optional = UserRegisterFormOptional(data=request.POST)
        try:
            form_required.clean()
            user = User.objects.create_user(username=request.POST['username'],

boards/templates/boards/board_blueboard_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Say::Project - Say it for MORE</title>
</head>
<body>

{% if error_message %}
<b>{{ error_message }}</b><br>
{% endif %}

<form action="{% url 'boards:board_blueboard_create' %}" method="post">
    {% csrf_token %}
    <label for="title">board name</label>
    <input type="text" name="title"><br>

    <label for="board_url">board url</label>
    <input type="text" name="board_url"><br>

    <label for="board_description">board description</label>
    <textarea name="board_description" cols="30" rows="4">

    </textarea>

    <button type="submit">Create Blueboard</button>
</form>


</body>
</html>

boards/templates/boards/board_nav_board_list.html
                <div class="container" style="font-size: 1.3em">
                    <div class="row justify-content-center">
                        <button  style="padding: 0px; margin: 0px; margin-top: auto; margin-left: 3em; margin-right: 3em" onclick="window.location.href='{% url 'boards:board_create_project_page' %}'"
                                 class="btn col-4 col-xs-12">
                                Create Project
                        </button>
                    </div>
                    <br><br><br><br>
                    <div class="row">
                        {% for highest in boards_activated_highest %}
                            <div class="col-sm-6 col-md-3 col-xs-6 col-12 text-center" style="padding: 0px">
                                <a href="#{# highest board link #}" style="text-decoration: none">
                                    <h4 class="type--uppercase">{{ highest.name }}</h4>
                                </a>
                                <ul class="list--hover">
                                    {% for under_board in highest.higher_board_related.all %}
                                        <li>
                                            <a href="#">{{ under_board.name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                                <br>
                            </div>
                        {% endfor %}
                    </div>
                </div>

boards/templates/boards/board_navigator_under.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="google-site-verification" content="iYIqT8x5FSbrffRjjLoJeldCp7coSGFXpUq_szd1qSs" />
        <title>Say::Project - Say it for MORE</title>
        <link rel="icon" href="{% static 'boards/favicon.ico' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'boards/css/stack-interface.css' %}" rel="stylesheet" type="text/css" media="all">
        <link href="{% static 'boards/css/socicon.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="{% static 'boards/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'boards/css/stack-interface.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'boards/css/theme.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'boards/css/custom.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="https://fonts.googleapis.com/css?family=Do+Hyeon" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:200,300,400,400i,500,600,700" rel="stylesheet">
    </head>
    <body data-smooth-scroll-offset="77">
        <div class="nav-container">
            <div>
                <nav class="bar bar-toggle">
                    <div class="container">
                        <div class="row align-items-center">
                            <div style="padding-left: 2em" class="col-6">
                                <div class="bar__module">
                                    <a href="{% url 'boards:board_index' %}">
                                        <img class="logo logo-dark" alt="logo"
                                             src="{% static 'boards/img/logo-dark.png' %}">
                                        <img class="logo logo-light" alt="logo"
                                             src="{% static 'boards/img/logo-light.png' %}"> </a>
                                </div>
                            </div>
                            <div class="col-6 d-flex justify-content-end">
                                <div class="bar__module">
                                    <a class="menu-toggle pull-right" href="#" data-notification-link="sidebar-menu">
                                        <i class="stack-interface stack-menu"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
                <div class="notification pos-right pos-top side-menu bg--white"
                     data-notification-link="sidebar-menu" data-animation="from-right">
                    <div class="side-menu__module pos-vertical-center text-center">
                        {% include 'boards/board_navigation.html' %}
                    </div>
                </div>
            </div>
        </div>
        <div class="main-container">
            <section>
                <div class="container">

                {# top article end #}
                    <div class="masonry">
                        <div class="row text-block">
                            {% if error_message %}
                            <div class="alert bg--error col-12 text-center">
                                <b>{{ error_message }}</b>
                            </div>
                            {% endif %}
                        </div>
                        <div class="row justify-content-center">
                            <button  style="padding: 0px; margin: 0px; margin-top: auto; margin-left: 3em; margin-right: 3em"
                                     onclick="window.location.href='{% url 'boards:board_create_project_page' %}'"
                                     class="btn col-4 col-xs-12">
                                    Create Project
                            </button>
                        </div>
                        <br><br>
                        <div class="masonry__container row masonry--active md d-block d-sm-block">
                                <div class="col-6 col-md-4 masonry__item ">
                                    <article class="feature feature-1">
                                        {% if board_self.image_file %}
                                            {% if board_self.points > 100 %}
                                                <a style="border-radius: 1em"
                                                   href="{% url 'boards:board_index_name' board_self.id %}" class="block title_img_top">
                                                    <div class="title_img_centered_text">
                                                        {{ board_self.name | truncatechars:25 }}
                                                    </div>
                                                    <img alt="Image" src="http://thl1110.jpg2.kr/{{ board_self.image_file.file }}">
                                                </a>
                                            {% else %}
                                                <div style="width: 100%">
                                                <a style="border-radius: 1em"
                                                        href="{% url 'boards:board_index_name' board_self.id %}" class="block title_img">
                                                    <div class="title_img_centered_text">
                                                        {{ board_self.name | truncatechars:25 }}
                                                    </div>
                                                    <img alt="Image" src="http://thl1110.jpg2.kr/{{ board_self.image_file.file }}">
                                                </a>

                                                </div>
                                            {% endif %}
                                            <script>
                                                var img = new Image();
                                                img.onload = function() { mr.masonry.updateLayout(); };
                                                img.src = "http://thl1110.jpg2.kr/{{ board_self.image_file.file }}"
                                            </script>
                                        {% else %}
                                            {% if board_self.points > 10 %}
                                                <div style="border-radius: 1em"
                                                        class="title_img_text_only">
                                                <a href="{% url 'boards:board_index_name' board_self.id %}">
                                                    <div class="title_img_centered_text_text_only">
                                                        {{ board_self.name | truncatechars:40 }}
                                                    </div>
                                                </a>
                                                </div>
                                            {% else %}
                                                <div style="border-radius: 1em"
                                                        class="title_img_text_only">
                                                <a href="{% url 'boards:board_index_name' board_self.id %}">
                                                    <div class="title_img_centered_text_text_only">
                                                        {{ board_self.name | truncatechars:40 }}
                                                    </div>
                                                </a>
                                                </div>
                                            {% endif %}
                                        {% endif %}
                                        <div class="feature__body boxed card">
                                            <div class="card__bottom text-center">
                                                <ul class="list-inline">
                                                    <li class="list-inline-item">
                                                        <div style="font-size: 0.9em;" class="card__action">
                                                            <a href="#"> <i style="color: #ff5e5e;" class="material-icons">favorite</i>
                                                                <span>{{ board_self.points }}</span> </a>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </article>
                                </div>
                            {% include 'boards/board_project_list_fragment.html' %}
                            {% block js %}
                                <script src="http://code.jquery.com/jquery-latest.js"></script>
                                <script src="{% static 'boards/js/el-pagination.js' %}"></script>
                                <script>
                                    $.endlessPaginate({paginateOnScroll: true,
                                                       paginateOnScrollMargin: 500,
                                                        });
                                    $.endlessPaginate({paginateOnScrollMargin: 400});
                                    $.endlessPaginate({paginateOnScrollMargin: 300});
                                    $.endlessPaginate({paginateOnScrollMargin: 200});
                                    $.endlessPaginate({paginateOnScrollMargin: 100});
                                    $.endlessPaginate({paginateOnScrollMargin: 1});
                                    $.endlessPaginate({paginateOnScrollMargin: 0});
                                </script>
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <div class="main-container">
            <footer class="footer-7 text-center-xs">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6"> <span class="type--fine-print">© <span class="update-year">
                        </span> Say::Project — All Rights Reserved</span>
                        </div>
                        <div class="col-sm-6 text-right text-center-xs">
                            <ul class="social-list list-inline">
                                <li><a href="#"><i class="socicon socicon-google icon icon--xs"></i></a></li>
                                <li><a href="#"><i class="socicon socicon-twitter icon icon--xs"></i></a></li>
                                <li><a href="#"><i class="socicon socicon-facebook icon icon--xs"></i></a></li>
                                <li><a href="#"><i class="socicon socicon-instagram icon icon--xs"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <script src="{% static 'boards/js/jquery-3.1.1.min.js' %}"></script>
        <script src="{% static 'boards/js/parallax.js' %}"></script>
        <script src="{% static 'boards/js/isotope.min.js' %}"></script>
        <script src="{% static 'boards/js/smooth-scroll.min.js' %}"></script>
        <script src="{% static 'boards/js/scripts.js' %}"></script>

    </body>

</html>

boards/templates/boards/board_register.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Say::Project - Say it for MORE</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'boards/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'boards/css/stack-interface.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'boards/css/theme.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="{% static 'boards/css/custom.css' %}" rel="stylesheet" type="text/css" media="all" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:200,300,400,400i,500,600,700" rel="stylesheet">

    </head>
    <body data-smooth-scroll-offset="77">
        <div class="nav-container"> </div>
        <div class="main-container">
            <section class="">
                <div class="container">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-md-6 col-lg-5" style="margin: 2em">
                            <div class="switchable__text">
                                <h2>회원가입</h2> <span>이미 회원이신가요? &nbsp;&nbsp; <a href="{% url 'boards:board_login' %}"> 로그인</a></span>
                                <hr class="short">
{#                            {% if form_required.has_error %}#}
{#                                <div class="alert bg--error col-12 text-center">#}
{#                                    <b>{{ form_required.non_field_errors }}</b>#}
{#                                </div >#}
{#                            {% endif %}#}
                            {% if error_message %}
                                <div class="alert bg--error col-12 text-center">
                                    <b>{{ error_message }}</b>
                                </div >
                            {% endif %}
                            {% if form_required.errors %}
                                <div class="alert bg--error col-12 text-center">
                                {% for error in form_required.non_field_errors  %}
                                    <b>{{ error|striptags }}</b>
                                {% endfor %}
                                </div>
                            {% endif %}
                                <form action="{% url 'boards:board_register' %}" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="row col-12">
                                    </div>
                                    <div class="row">
                                        {{ form_required.errors }}
                                        {{ form_required }}
                                    </div>
                                    <br><hr class="short">
                                    <div class="row col-12">
                                        <p style="text-align: center; color: #0066cc" class="text-center">
                                            아래로는 선택입력사항입니다.
                                        </p>
                                    </div>
                                    <div class="row">
                                    {{ form_optional.errors }}
                                        {{ form_optional }}
                                    </div>
                                    <div class="row">
                                        <div style="margin-top: 2em" class="col-12"> <button type="submit" class="btn btn--primary">Create Account</button> </div>
                                        <div class="col-12">  </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <script src="{% static 'boards/js/jquery-3.1.1.min.js' %}"></script>
        <script src="{% static 'boards/js/parallax.js' %}"></script>
        <script src="{% static 'boards/js/smooth-scroll.min.js' %}"></script>
        <script src="{% static 'boards/js/scripts.js' %}"></script>
    </body>

</html>

boards/templates/boards/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>