polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

todaycomment/urls.py
from django.urls import path

from . import views

app_name = 'todaycomment'
urlpatterns = [
    path('', views.com_index, name='com_index'),
    path('post', views.com_post, name='com_post'),
    path('delete', views.com_delete, name='com_delete'),
]

tutorialPoll/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

from boards.views import assetlink

urlpatterns = [
    path('', include('boards.urls')),
    # path('todaycomment/', include('todaycomment.urls')),
    # path('boards/', include('boards.urls')),
    # path('polls/', include('polls.urls')),
    path('say/admin/', admin.site.urls),

    re_path(r'^summernote/', include('django_summernote.urls')),

    re_path(r'^\.well-known/assetlinks\.json', assetlink.as_view()),

    path('API/', include('router.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todaycomment/models.py
from django.db import models

# Create your models here.


class Comment_list(models.Model):
    name = models.CharField(max_length=20)
    comment_text = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_created='True')
    upvote = models.IntegerField(default=0)
    downvote = models.IntegerField(default=0)

    def __str__(self):
        return self.comment_text

todaycomment/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from django.urls import reverse

from django.http import HttpResponseRedirect
from .models import Comment_list

# Create your views here.

def com_index(request):
    comment_list = Comment_list.objects.order_by('created_at').reverse()
    return render(request, 'todaycomment/index.html', {'comment_list': comment_list})

def com_post(request):
    try:
        C = Comment_list(comment_text=request.POST['comment_text'], created_at=timezone.now())
        C.save()
        return HttpResponseRedirect(reverse('todaycomment:com_index'))
    except:
        return render(request, 'todaycomment/index.html', {'error_message': "댓글을 쓰는데에 실패했습니다."})

def com_delete(request):
    C = get_object_or_404(Comment_list, id=request.POST['comment_del'])
    try:
        C.delete()
        return HttpResponseRedirect(reverse('todaycomment:com_index'))
    except:
        return render(request, 'todaycomment/index.html', {'error_message' : "댓글을 삭제하는데에 실패했습니다."})

todaycomment/templates/todaycomment/index.html
<!DOCTYPE html>
<html lang="ko" >
{% load static %}
<head>
  <meta charset="UTF-8">
  <title>Poster</title>
     <meta name="viewport" content="width=device-width, initial-scale=1"/>
     <link rel="stylesheet" href="{% static 'todaycomment/css/style.css' %}">
    <script>
    function resize(obj) {
      obj.style.height = "1px";
      obj.style.height = (12+obj.scrollHeight)+"px";
    }
    </script>
</head>

<body>

 <div id="pagewrap">
  <form class="frm" action="{% url 'todaycomment:com_post' %}" method="post">
   {% csrf_token %}
      <div class="paper">
          <div class="paper-content">
            <textarea name="comment_text" autofocus placeholder="오늘 하루&#10;안녕하셨나요?"></textarea>
          </div>
      </div>
       <div class="submit-button">
         <button type="submit" id="submit">post</button>
       </div>
  </form>

  <div class="feeds">
   <ul id="comments">
    {% for list in comment_list %}
        <li>{{ list.comment_text|linebreaks }}</li>
        <form action="">
        {% csrf_token %}
            <button type="submit" id="submit">수정</button>
        </form>
        <form action="{% url 'todaycomment:com_delete' %}" method="post">
        {% csrf_token %}
            <button type="submit" value="{{ list.id }}" name="comment_del">삭제</button>
        </form>
    {% endfor %}
    <li>Let's get farted!</li>
   </ul>
  </div>
 </div>

<script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>

</body>

</html>